<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="24134" started-at="2014-06-05T03:38:51Z" finished-at="2014-06-05T03:39:15Z">
    <groups>
      <group name="remote-integration">
        <method signature="CardFraudulentServiceTest.basicTest()[pri:0, instance:com.example.tutorial.ws.integration.CardFraudulentServiceTest@ea083a]" name="basicTest" class="com.example.tutorial.ws.integration.CardFraudulentServiceTest"/>
      </group> <!-- remote-integration -->
    </groups>
    <test name="Default test" duration-ms="24134" started-at="2014-06-05T03:38:51Z" finished-at="2014-06-05T03:39:15Z">
      <class name="com.example.tutorial.ws.integration.CardFraudulentServiceTest">
        <test-method status="PASS" signature="springTestContextBeforeTestClass()[pri:0, instance:com.example.tutorial.ws.integration.CardFraudulentServiceTest@ea083a]" name="springTestContextBeforeTestClass" is-config="true" duration-ms="16" started-at="2014-06-04T22:38:51Z" finished-at="2014-06-04T22:38:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestClass -->
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:com.example.tutorial.ws.integration.CardFraudulentServiceTest@ea083a]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="2452" started-at="2014-06-04T22:38:51Z" depends-on-methods="org.springframework.test.context.testng.AbstractTestNGSpringContextTests.springTestContextBeforeTestClass" finished-at="2014-06-04T22:38:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:com.example.tutorial.ws.integration.CardFraudulentServiceTest@ea083a]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="1" started-at="2014-06-04T22:38:53Z" finished-at="2014-06-04T22:38:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.example.tutorial.ws.integration.CardFraudulentServiceTest.basicTest() throws java.net.URISyntaxException,org.wtf.interoperability.ws.vo.RequiredHeaderMissingFault,org.wtf.interoperability.ws.vo.SystemUnavailableFault]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="FAIL" signature="basicTest()[pri:0, instance:com.example.tutorial.ws.integration.CardFraudulentServiceTest@ea083a]" name="basicTest" duration-ms="21625" started-at="2014-06-04T22:38:53Z" finished-at="2014-06-04T22:39:15Z">
          <exception class="javax.xml.ws.soap.SOAPFaultException">
            <message>
              <![CDATA[An error was discovered processing the <wsse:Security> header.]]>
            </message>
            <full-stacktrace>
              <![CDATA[javax.xml.ws.soap.SOAPFaultException: An error was discovered processing the <wsse:Security> header.
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:157)
	at $Proxy35.report(Unknown Source)
	at com.example.tutorial.ws.integration.CardFraudulentServiceTest.basicTest(CardFraudulentServiceTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200)
	at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.apache.cxf.binding.soap.SoapFault: An error was discovered processing the <wsse:Security> header.
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.unmarshalFault(Soap11FaultInInterceptor.java:84)
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:51)
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:40)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:113)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:69)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:34)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:845)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1624)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1513)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1318)
	at org.apache.cxf.io.CacheAndWriteOutputStream.postClose(CacheAndWriteOutputStream.java:56)
	at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:223)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:632)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:570)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:479)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:382)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:335)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:135)
	... 33 more
]]>
            </full-stacktrace>
          </exception> <!-- javax.xml.ws.soap.SOAPFaultException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicTest -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:com.example.tutorial.ws.integration.CardFraudulentServiceTest@ea083a]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="2" started-at="2014-06-04T22:39:15Z" finished-at="2014-06-04T22:39:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.example.tutorial.ws.integration.CardFraudulentServiceTest.basicTest() throws java.net.URISyntaxException,org.wtf.interoperability.ws.vo.RequiredHeaderMissingFault,org.wtf.interoperability.ws.vo.SystemUnavailableFault]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestClass()[pri:0, instance:com.example.tutorial.ws.integration.CardFraudulentServiceTest@ea083a]" name="springTestContextAfterTestClass" is-config="true" duration-ms="0" started-at="2014-06-04T22:39:15Z" finished-at="2014-06-04T22:39:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestClass -->
      </class> <!-- com.example.tutorial.ws.integration.CardFraudulentServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
